export enum ImpressionCode {
  START_PGN_IMPORT = 1,
  PGN_EXPORT = 2,
  TREE_SELECT_LEFT = 3,
  TREE_SELECT_RIGHT = 4,
  TREE_SELECT_UP = 5,
  TREE_SELECT_DOWN = 6,
  TREE_TRASH_SELECTED = 7,
  TREE_FLIP_REPERTOIRE_COLOR = 8,
  ENTER_BUILD_MODE = 9,
  ENTER_STUDY_MODE = 10,
}
