const Config = {
  AUTH0_AUDIENCE: 'studyopenings-api',
  AUTH0_DOMAIN: 'studyopenings.auth0.com',
  AUTH0_CLIENT_ID: '4N3xZuND2puazbhvLdpLpp17Bv19Fn0g',

  CHESSBOARD_MOVE_SPEED_MS: 100,
  OPPONENT_FIRST_MOVE_DELAY_MS: 500,
  OPPONENT_REPLY_DELAY_MS: 200,
  NEXT_LINE_DELAY_MS: 500,
  TREE_ROW_PADDING_PX_PER_INDENT: 15
};