export const Config = {
  AUTH0_AUDIENCE: 'studyopenings-api',
  AUTH0_DOMAIN: 'studyopenings.auth0.com',
  AUTH0_CLIENT_ID: '4N3xZuND2puazbhvLdpLpp17Bv19Fn0g',

  OPPONENT_FIRST_MOVE_DELAY_MS: 600,
  OPPONENT_REPLY_DELAY_MS: 600,
  NEXT_LINE_DELAY_MS: 1200,

  WRONG_MOVES_FOR_ANSWER: 2,
  WRONG_MOVES_FOR_HINT: 1,

  MAXIMUM_LINE_DEPTH_IN_PLY: 80,
  MAXIMUM_TREE_NODES_PER_REPERTOIRE: 1000,
};
